### ISSUE TITLE
Git repo + downloaded zips are "corrupted" (file + link to same name) 

### ISSUE THREAD

**Issue by julianrendell** [philbowles/H4#1]
`src/H4.h` and `src/inc/H4.h` are aliasing each other/there's a mismatch between a link and the real file content.

Unzipping the zip file (release & current `master` branch) leads to a an error and the link is not created, nor is the full file content created.

Checkout from git leads to a git error and a weird state- again with regard to the linked/aliased file.

This is on OS X.

Workaround: copy the content from the 'raw' view on GitHub.

**Comment by philbowles** [comment]
All fixed by 1.0.1
