### ISSUE TITLE
pin task to a core (esp32)

### ISSUE THREAD

**Issue by RomeHein** [philbowles/H4#3]
Would it be possible to pin (or queue) a certain task to a core?
I tried to read the code of H4, but it's fairly complex and could not figure if that was already the case.
My use case:

I'm trying to integrate H4 to my project (available here: https://github.com/RomeHein/ESPecial). This is a firmware with a lot of features, including one which is a huge bottleneck in term of performance: Telegram.
I'm using this library: https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot, which has the big disadvantage to not be async (Telegram does work with websockets but that would mean async https, which is not working on esp32 atm). This means that the esp32 has to poll Telegram server every sec or so. Which block the core during the connection. Before integrating H4 I was splitting this task to the core 1 and the rest of the tasks to core 0 (like checking gpio's state) which was working ok.

Thanks for your help

**Comment by philbowles** [comment]
Wow, sorry I didn't see this, I don't come here often. I have to say to start with that mixing sync and async is generally a BAD idea. However I will think about this and see if pinning it to core 0 will break anything else. To get faster responsenext time, you will find me in this FB group pretty much every day: [https://www.facebook.com/groups/h4plugins](https://www.facebook.com/groups/h4plugins)
